namespace fusion_2.Model
{
    public class register
    {
        public
class
IndustryDto
        {
            public
            string
            CompanyName
            {
                get
                ;
                set
                ;
            }
            public
            string
            IndustryType
            {
                get
                ;
                set
                ;
            }
           
           
            public
            string
            State
            {
                get
                ;
                set
                ;
            }
            public
            string
            Country
            {
                get
                ;
                set
                ;
            }
            public
            string
            ContactNo
            {
                get
                ;
                set
                ;
            }
            public
            string
            Email
            {
                get
                ;
                set
                ;
            }
            public
            string
            Password
            {
                get
                ;
                set
                ;
            }
            public
            string
            ConformPassword
            {
                get
                ;
                set
                ;
            }
    }
    }
}
